---
# tasks file for apache-mod-evasive

- name: Include OS-family-specific variables
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Install packages
  ansible.builtin.package:
    name: "{{ apache_mod_evasive_packages }}"
    state: present

- name: Configure Apache mod_evasive
  ansible.builtin.template:
    src: evasive.conf.j2
    dest: "{{ apache_mod_evasive_conf_filepath }}"
    owner: root
    group: root
    mode: '0644'

  notify: Restart Apache2
